name: test

on:
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Testing Swift Package
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.6"
    - name: Run tests
      run: swift test --configuration debug -Xlinker -rpath -Xlinker "$(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.6.1/macosx"
