name: test

on:
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Testing Swift Package
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.6"
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.4'
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test
