name: test

on:
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Testing Swift Package
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test
