name: test

on:
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Testing Swift Package
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.6"
    - name: Run tests
      run: swift test 2>&1 | xcpretty
